[project]
name = "customer-support-agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "datasets>=5.0.0",
    "ipykernel>=7.3.0",
    "jq>=1.12.0",
    "langchain-community>=0.4.2",
    "langchain-experimental>=0.4.2",
    "langchain-huggingface>=1.2.2",
    "logfire>=4.39.0",
    "pandas>=3.0.5",
    "sentence-transformers>=5.6.1",
]
